package com.backend.database;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.Optional;

/**
 * Exposes access to User records in the database through the User class.
 * <p>
 * Implementation gets auto-generated by the framework.
 * @author JaarmaCo
 * @version 1.0
 * @since 2025-09-18
 */
public interface UserRepository extends JpaRepository<User, String> {

    /**
     * Finds a user through their email address.
     *
     * @param email Email of the user.
     * @return The located user or null.
     */
    @Query("SELECT u FROM User u WHERE u.email=:email")
    Optional<User> findByEmail(@Param("email") String email);
}
