#!/usr/bin/env bash

#
# bash script file.
#
# Creates a new database and then runs the mock initializer script.
#

set -e

_yes_no() {
  local yn
  while true; do
    read -p '[y/n]: ' yn
    case "$yn" in
    [Yy]*)
      return 0
      ;;
    [Nn]*)
      return 1
      ;;
    esac
  done
}

_install_gpg_package() {

  if [[ $(which apt) ]]; then
    sudo apt update
    sudo apt install -y gpg
  elif [[ $(which dnf) ]]; then
    sudo dnf -y install gnupg2
  elif [[ $(which pacman) ]]; then
    sudo pacman --noconfirm -S gnupg
  elif [[ $(which brew) ]]; then
    brew install gnupg
  fi
}

_install_psql_package() {

  if [[ $(which apt) ]]; then
    sudo apt update
    sudo apt install -y psql
  elif [[ $(which dnf) ]]; then
    sudo dnf -y install psql
  elif [[ $(which pacman) ]]; then
    sudo pacman --noconfirm -S psql
  elif [[ $(which brew) ]]; then
    brew install psql
  fi
}

_activate_postgres() {

  if [[ $(which systemctl) ]]; then
    if [[ "$(systemctl is-active postgresql.service)" != "active" ]]; then
      echo 'PostgresSQL was not running. (sudo) Attempting to activate it...'
      sudo systemctl start postgresql.service
    fi
  elif [[ $(which service) ]]; then
    if ! service postgresql status >/dev/null; then
      echo 'PostgresSQL was not running. (sudo) Attempting to activate it...'
      sudo service postgresql start
    fi
  else
    echo "Could not find a suitable daemon manager, please ensure Postgres is started yourself."
  fi
}

main() {

  local QUICK=
  local FORCE=
  local USEME
  local OPTIONS=$(getopt --longoptions 'quick-setup,force,use-me' --options 'Qf' -- "$@")

  local i
  for i in $OPTIONS; do
    case "$i" in
      -Q|--quick-setup)
        shift
        QUICK=1
        ;;
      -f|--force)
        shift
        FORCE=1
        ;;
      --use-me)
        shift
        USEME=1
        ;;
      --)
        break
        ;;
      *)
        echo "Skipping unknown argument: $i"
        ;;
    esac
  done

  if [[ -z $(which gpg) ]]; then
    echo 'This script will not run without access to the Gnu Privacy Guard software (gnupg).'
    if ! [[ $QUICK ]]; then
      printf 'Install package? '
      _yes_no
    fi
    _install_gpg_package
  fi

  if [[ -z $(which psql) ]]; then
    echo 'Missing psql (PostgresSQL) executable.'
    if ! [[ $QUICK ]]; then
      printf 'Install package? '
      _yes_no
    fi
    _install_psql_package
  fi

  _activate_postgres

  echo 'Ensuring access as postgres, you may be prompted for your sudo password here.'
  echo
  echo 'If you are unsure about continuing this script press CTRL+C to exit here and inspect'
  echo 'the source code before continuing.'
  echo

  if ! [[ $USEME ]]; then 
    sudo -u postgres echo 'Access as user postgres granted.'
  fi

  sleep 1
  clear

  echo "  ____                                          "
  echo " |  _ \\                                         "
  echo " | |_) | ___ _ __   ___                         "
  echo " |  _ < / _ \\ '_ \\ / _ \\                        "
  echo " | |_) |  __/ | | |  __/                        "
  echo " |____/_\\___|_|_|_|\\___|           _____  ____  "
  echo "  / ____|     | |                 |  __ \\|  _ \\ "
  echo " | (___  _ __ | |__   ___ _ __ ___| |  | | |_) |"
  echo "  \\___ \\| '_ \\| '_ \\ / _ \\ '__/ _ \\ |  | |  _ < "
  echo "  ____) | |_) | | | |  __/ | |  __/ |__| | |_) |"
  echo " |_____/| .__/|_| |_|\\___|_|  \\___|_____/|____/ "
  echo "        | |                                     "
  echo "        |_|                                     "
  tee <<EOF

Creation script for the BeneSphere DB.

EOF

  if [[ $QUICK ]]; then
    echo 'Running quick setup...'
  fi

  if [[ $FORCE ]]; then
    echo 'Force specified, will not prompt for confirmation'
  fi

  local BACKEND_ROOT=$(realpath "../../../")
  local DEFAULT_PASSPHRASE_FILE=$HOME/.benesphere_db/.secret/benesphere-pw.txt
  local PASSPHRASE_FILE

  if [[ $FORCE ]]; then
    echo "Force specified. Continuing anyway..."
  else
    tee <<EOF
OBS!

This script will destroy any existing instance of this database, run at your own risk.

Continue? 
EOF
    _yes_no
  fi

  echo "Looking for default credentials in $DEFAULT_PASSPHRASE_FILE"

  if [ -f $DEFAULT_PASSPHRASE_FILE ]; then
    echo "Found passphrase at default path $DEFAULT_PASSPHRASE_FILE"
    printf "Use it? "
    if [[ $QUICK ]] || _yes_no; then
      PASSPHRASE_FILE=$DEFAULT_PASSPHRASE_FILE
    fi
  else
    echo "None found in $DEFAULT_PASSPHRASE_FILE"
    DEFAULT_PASSPHRASE_FILE=$BACKEND_ROOT/.benesphere_db/.secret/benesphere-pw.txt
    echo "Trying $DEFAULT_PASSPHRASE_FILE"
    if [ -f $DEFAULT_PASSPHRASE_FILE ]; then
      echo "Found passphrase at default path $DEFAULT_PASSPHRASE_FILE"
      printf "Use it? "
      if [[ $QUICK ]] || _yes_no; then
        PASSPHRASE_FILE=$DEFAULT_PASSPHRASE_FILE
      fi
    else
      echo "No default option found. You'll have to enter it manually."
    fi
  fi

  if ! [[ $QUICK ]] && [[ -z $PASSPHRASE_FILE ]]; then
    read -e -p 'Enter passphrase file (or nothing to use a default password): ' PASSPHRASE_FILE
  fi

  if [[ $PASSPHRASE_FILE ]]; then
    PASSPHRASE_FILE=${PASSPHRASE_FILE/#\~/$HOME}
    PASSPHRASE_FILE=$(realpath $PASSPHRASE_FILE)

    echo "Reading passphrase from ${PASSPHRASE_FILE}"
    local PASS=$(gpg --passphrase-file $PASSPHRASE_FILE --pinentry-mode loopback -d ./dbpasswords/benesphere.key.gpg)

    if [[ -z $PASS ]]; then
      echo 'Failed to decrypt password file.'
      exit 1
    fi

  else
    PASS="$(sha256sum <$0 | cut -d ' ' -f1)"
    echo "No passphrase file provided, choosing default password ${PASS}"
  fi

  local CONNSTRING=postgresql://benesphere_sudo:${PASS}@localhost:5432/benesphere_db
  local USR_CONNSTRING=postgresql://benesphere:J2-3%2F5=941Adv@localhost:5432/benesphere_db

  echo 'Creating database...'
  if [[ $USEME ]]; then
    psql -U $(whoami) -v benesphere_password=$PASS -f "$(dirname "$0")/user-db-setup.sql"
  else
    sudo -u postgres psql -v benesphere_password=$PASS -f "$(dirname "$0")/user-db-setup.sql"
  fi
  echo 'Creating tables...'
  if [[ $USEME ]]; then
    psql -U $(whoami) $CONNSTRING -f "$(dirname $0)/setup.sql"
  else
    sudo -u postgres psql $CONNSTRING -f "$(dirname $0)/setup.sql"
  fi
  printf 'Insert mock data? '
  if [[ $QUICK ]] || _yes_no; then
    echo 'Inserting mock data...'
    if [[ $USEME ]]; then
      psql -U $(whoami) $CONNSTRING -f "$(dirname $0)/mockdata.sql"
    else
      sudo -u postgres psql $CONNSTRING -f "$(dirname $0)/mockdata.sql"
    fi
  fi

  echo 'Setting up permissions for benesphere user.'
  sudo -u postgres psql $CONNSTRING -f "$(dirname $0)/permissions.sql"

  printf 'Creation complete.'
  if ! [[ $QUICK ]]; then
    printf ' Create a login script? '
    _yes_no;
  else
    echo
  fi

  mkdir -p $BACKEND_ROOT/.benesphere_db

  if [[ $USEME ]]; then
    echo -e "psql -U $(whoami) '$USR_CONNSTRING'" >$BACKEND_ROOT/.benesphere_db/login.sh
  else
    echo -e "sudo -u postgres psql '$USR_CONNSTRING'" >$BACKEND_ROOT/.benesphere_db/login.sh
  fi
  echo "Created login script for benesphere at $(realpath $BACKEND_ROOT/.benesphere_db/login.sh)"

  if [[ $USEME ]]; then
    echo -e "psql -U $(whoami) '$CONNSTRING'" >$BACKEND_ROOT/.benesphere_db/login-sudo.sh
  else
    echo -e "sudo -u postgres psql '$CONNSTRING'" >$BACKEND_ROOT/.benesphere_db/login-sudo.sh
  fi
  echo "Created login script for benesphere_sudo at $(realpath $BACKEND_ROOT/.benesphere_db/login-sudo.sh)"
}

main $@
