package com.backend.database.repositories;

import com.backend.database.entities.*;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.Optional;

/**
 * Exposes access to Charity records in the database through the Charity class
 *
 * Implementation gets auto-generated by the framework
 * @author Ludvighygrell
 * @version 1.0
 * @since 2025-09-18
 */
public interface CharityRepository extends JpaRepository<Charity, String>{

    /**
     * Returns a charity given its organization ID.
     *
     * @param orgId the organization ID of the charity.
     * @return the charity, or null if it could not be found.
     */
    @Query("SELECT c FROM Charities WHERE c.orgId=:orgId")
    Optional<Charity> findByOrgID(@Param("orgId") String orgId);

}
